FROM golang:1.10 as build-stage

# Set WORKDIR to project path in GOPATH
WORKDIR /go/src/cd.splunkdev.com/core-services/ssc-observation

# Copy repository
COPY . /go/src/cd.splunkdev.com/core-services/ssc-observation/
